package skill

import (
	"strings"
	"testing"
)

// sampleData exercises every branch of the react codegen template: a list query
// with query params, a query with a path param, a mutation with a body, and a
// mutation with a path param only.
func sampleData() CodegenData {
	return CodegenData{
		Tag:            "Khoa",
		ProxyBase:      "/env/dev/api",
		HooksModule:    "./khoa.hooks",
		HasQueries:     true,
		HasMutations:   true,
		UsesOperations: true,
		Endpoints: []CodegenEndpoint{
			{
				Op: "getKhoaList", HookName: "useKhoaList", Method: "GET",
				Path: "/khoa", PathExpr: "'/khoa'", IsQuery: true, HasQuery: true, HasOp: true,
			},
			{
				Op: "getKhoaById", HookName: "useKhoaById", Method: "GET",
				Path: "/khoa/{id}", PathExpr: "`/khoa/${vars.id}`", IsQuery: true,
				PathParams: []string{"id"}, NeedsVars: true, HasOp: true,
			},
			{
				Op: "createKhoa", HookName: "useCreateKhoa", Method: "POST",
				Path: "/khoa", PathExpr: "'/khoa'", HasBody: true, HasOp: true,
			},
			{
				Op: "deleteKhoa", HookName: "useDeleteKhoa", Method: "DELETE",
				Path: "/khoa/{id}", PathExpr: "`/khoa/${vars.id}`",
				PathParams: []string{"id"}, NeedsVars: true, HasOp: true,
			},
			{
				// No operationId in the spec -> falls back to `unknown`, no OpRes ref.
				Op: "get_khoa_stats", HookName: "useGetKhoaStats", Method: "GET",
				Path: "/khoa/stats", PathExpr: "'/khoa/stats'", IsQuery: true, HasOp: false,
			},
		},
	}
}

func TestReactCodegenRenders(t *testing.T) {
	// packDir is the repo root (two levels up from internal/skill).
	p, err := LoadPack("../..", "react")
	if err != nil {
		t.Fatalf("load react pack: %v", err)
	}
	if p.Codegen == nil {
		t.Fatal("react pack has no codegen section")
	}

	out, err := p.RenderCodegen("../..", sampleData())
	if err != nil {
		t.Fatalf("render codegen: %v", err)
	}

	hooks := string(out["hooks"])
	for _, want := range []string{
		"// generated by sr pull — do not edit",
		"const BASE = '/env/dev/api'",
		"export function useKhoaList(",
		"export function useKhoaById(vars: { id: string;",
		"export function useCreateKhoa()",
		"export function useDeleteKhoa()",
		"queryKey: ['Khoa', 'getKhoaList', vars]",
		"useMutation({",
		"`/khoa/${vars.id}`",
		"invalidateQueries({ queryKey: ['Khoa'] })",
		"request<OpRes<'getKhoaList'>>",  // op present -> typed
		"request<unknown>('GET', '/khoa/stats')", // op absent -> unknown fallback
		"import type { operations } from './types'", // emitted because UsesOperations
	} {
		if !strings.Contains(hooks, want) {
			t.Errorf("hooks output missing %q\n---\n%s", want, hooks)
		}
	}
	// A mutation-only import must not appear when queries exist and vice versa —
	// here both exist, so all three symbols should be imported exactly once.
	if strings.Count(hooks, "@tanstack/react-query") != 1 {
		t.Errorf("expected exactly one react-query import line:\n%s", hooks)
	}

	index := string(out["index"])
	if !strings.Contains(index, "export * from './khoa.hooks'") {
		t.Errorf("index missing hooks re-export:\n%s", index)
	}
	if !strings.Contains(index, "export * from './types'") {
		t.Errorf("index missing types re-export:\n%s", index)
	}
}
