package skill

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestFetchConfluenceEndToEnd drives the whole Fetch() pipeline for a Confluence
// source against a local server: HTTP GET (with Basic auth) -> ADF parse ->
// markdown file -> digest -> cache hit on the second call.
func TestFetchConfluenceEndToEnd(t *testing.T) {
	heading := node("heading", text("Mục tiêu"))
	heading["attrs"] = map[string]any{"level": 2}
	adf := map[string]any{"version": 1, "type": "doc", "content": []map[string]any{
		heading,
		node("paragraph", text("Nội dung")),
	}}
	resp := buildConfluenceResponse(t, "Spec Login", adf)

	var hits int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
		user, pass, ok := r.BasicAuth()
		if !ok || user != "me@acme.vn" || pass != "secret-token" {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
		if r.URL.Path != "/wiki/api/v2/pages/12345" {
			w.WriteHeader(http.StatusNotFound)
			return
		}
		w.Write(resp)
	}))
	defer srv.Close()

	orig := confluenceBaseURL
	confluenceBaseURL = func(string) string { return srv.URL }
	defer func() { confluenceBaseURL = orig }()

	dir := t.TempDir()
	t.Setenv("CONFLUENCE_TOKEN", "secret-token")

	opts := FetchOptions{
		From:       "https://acme.atlassian.net/wiki/spaces/HR/pages/12345/Spec-Login",
		Email:      "me@acme.vn",
		ProjectDir: dir,
	}
	d, _, err := Fetch(opts)
	if err != nil {
		t.Fatal(err)
	}
	if d.Source != "confluence" || d.Title != "Spec Login" {
		t.Errorf("digest = %+v", d)
	}
	if d.File != "docs/specs/spec-login.md" {
		t.Errorf("file = %q", d.File)
	}
	if len(d.Sections) != 1 || d.Sections[0] != "Mục tiêu" {
		t.Errorf("sections = %v", d.Sections)
	}

	md, err := os.ReadFile(filepath.Join(dir, d.File))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(md), "generated by sr fetch") || !strings.Contains(string(md), "## Mục tiêu") {
		t.Errorf("markdown file wrong:\n%s", md)
	}

	// Second call: same content -> cache hit, same digest.
	d2, _, err := Fetch(opts)
	if err != nil {
		t.Fatal(err)
	}
	if d2.ContentHash != d.ContentHash {
		t.Errorf("content hash changed: %q vs %q", d.ContentHash, d2.ContentHash)
	}
	if hits < 2 {
		t.Errorf("expected the server to be hit on both calls, got %d", hits)
	}
}

// TestFetchGsheetEndToEnd drives Fetch() for a link-shared sheet (no auth).
func TestFetchGsheetEndToEnd(t *testing.T) {
	csv := "ID,Bước,Kỳ vọng\nTC1,Mở trang,Thấy form\n"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/spreadsheets/d/SHEET123/export") {
			w.WriteHeader(http.StatusNotFound)
			return
		}
		w.Write([]byte(csv))
	}))
	defer srv.Close()

	orig := gsheetExportBase
	gsheetExportBase = srv.URL
	defer func() { gsheetExportBase = orig }()

	dir := t.TempDir()
	d, jsonOut, err := Fetch(FetchOptions{
		From:       "https://docs.google.com/spreadsheets/d/SHEET123/edit#gid=7",
		ProjectDir: dir,
	})
	if err != nil {
		t.Fatal(err)
	}
	if d.Source != "gsheet" || len(d.Tables) != 1 || d.Tables[0].Rows != 1 {
		t.Errorf("digest = %+v", d)
	}
	md, err := os.ReadFile(filepath.Join(dir, d.File))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(md), "| TC1 | Mở trang | Thấy form |") {
		t.Errorf("markdown wrong:\n%s", md)
	}
	if !strings.Contains(jsonOut, "\"source\": \"gsheet\"") {
		t.Errorf("digest json missing source:\n%s", jsonOut)
	}
}

// TestFetchAliasResolution: an alias in config resolves to a real URL before detect.
func TestFetchAliasResolution(t *testing.T) {
	csv := "A,B\n1,2\n"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(csv))
	}))
	defer srv.Close()
	orig := gsheetExportBase
	gsheetExportBase = srv.URL
	defer func() { gsheetExportBase = orig }()

	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, ".skillrunner"), 0o755)
	cfg := `{"sources":{"tc":"https://docs.google.com/spreadsheets/d/ALIASED/edit#gid=0"}}`
	os.WriteFile(filepath.Join(dir, ".skillrunner", "fetch.json"), []byte(cfg), 0o644)

	d, _, err := Fetch(FetchOptions{From: "tc", ProjectDir: dir})
	if err != nil {
		t.Fatal(err)
	}
	if d.Source != "gsheet" {
		t.Errorf("alias did not resolve: %+v", d)
	}
}
