package skill

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDetectSource(t *testing.T) {
	cases := []struct {
		url       string
		kind      string
		id        string
		gid       string
		cacheSlug string
		wantErr   bool
	}{
		{
			url: "https://acme.atlassian.net/wiki/spaces/HR/pages/12345/Spec-dang-nhap",
			kind: "confluence", id: "12345", cacheSlug: "confluence-12345",
		},
		{
			url: "https://acme.atlassian.net/wiki/pages/999", // no space segment
			kind: "confluence", id: "999", cacheSlug: "confluence-999",
		},
		{
			url: "https://docs.google.com/spreadsheets/d/1AbC_dEf-123/edit#gid=42",
			kind: "gsheet", id: "1AbC_dEf-123", gid: "42", cacheSlug: "gsheet-1AbC_dEf-123-42",
		},
		{
			url: "https://docs.google.com/spreadsheets/d/1AbC_dEf-123/edit",
			kind: "gsheet", id: "1AbC_dEf-123", gid: "", cacheSlug: "gsheet-1AbC_dEf-123",
		},
		{url: "https://acme.atlassian.net/wiki/spaces/HR/overview", wantErr: true}, // no page id
		{url: "https://example.com/foo", wantErr: true},
	}
	for _, c := range cases {
		src, err := detectSource(c.url)
		if c.wantErr {
			if err == nil {
				t.Errorf("%s: expected error", c.url)
			}
			continue
		}
		if err != nil {
			t.Errorf("%s: %v", c.url, err)
			continue
		}
		if src.kind != c.kind || src.id != c.id || src.gid != c.gid || src.cacheSlug != c.cacheSlug {
			t.Errorf("%s: got %+v", c.url, src)
		}
	}
}

func TestFetchCacheRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "docs", "context", "fetch-x.json")
	d := &FetchDigest{Source: "confluence", Title: "T", ContentHash: "sha256:abc"}
	writeCachedFetch(path, d)

	got, ok := readCachedFetch(path, "sha256:abc")
	if !ok || got.Title != "T" {
		t.Fatalf("cache hit failed: ok=%v got=%+v", ok, got)
	}
	if _, ok := readCachedFetch(path, "sha256:different"); ok {
		t.Error("hash mismatch should miss")
	}
}

func TestWriteGeneratedGuard(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.md")

	if err := writeGenerated(path, "# hi\n"); err != nil {
		t.Fatal(err)
	}
	body, _ := os.ReadFile(path)
	if !strings.HasPrefix(string(body), "<!-- generated by sr fetch") {
		t.Errorf("missing header: %q", body)
	}
	// Re-writing our own file is fine.
	if err := writeGenerated(path, "# again\n"); err != nil {
		t.Errorf("rewrite own file: %v", err)
	}
	// Refuse to clobber a foreign file.
	foreign := filepath.Join(dir, "foreign.md")
	os.WriteFile(foreign, []byte("hand written\n"), 0o644)
	if err := writeGenerated(foreign, "x"); err == nil {
		t.Error("should refuse to overwrite a non-generated file")
	}
}
