package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// `sr home` — where the skill pool is, and how to say so.
//
// This is the one command that must work when nothing else does: if the pointer
// is missing or stale, every other verb fails with "no skill.json found", and
// the user needs something that reports the state instead of dying of it. So it
// resolves lazily and prints a diagnosis rather than calling fatal.

// shimName is the short alias installed alongside the real binary. Both names
// stay valid — the wrapper only forwards, so `sr` and `skillrunner` cannot drift.
const shimName = "sr"

// runHome performs the requested mutations (in a deliberate order: record the
// pool first, then write wrappers), then always prints where the manifest
// resolves from. Printing last makes `sr home --set X` self-verifying.
func runHome(set string, shims bool) error {
	if set != "" {
		if err := writePointer(set); err != nil {
			return err
		}
	}
	if shims {
		if err := writeShims(); err != nil {
			return err
		}
	}
	return reportHome()
}

// writePointer records the pool directory at ~/.skillrunner/home.
//
// A directory with no manifest in it is rejected rather than recorded: a pointer
// that looks configured but resolves to nothing is precisely the failure mode
// this whole ladder exists to end.
func writePointer(dir string) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolve %s: %w", dir, err)
	}
	if !fileExists(filepath.Join(abs, manifestName)) {
		return fmt.Errorf("%s has no %s in it — point --set at the skill pool directory (the one holding %s and packs/)", abs, manifestName, manifestName)
	}
	p, err := pointerPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(p, []byte(abs+"\n"), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", p, err)
	}
	fmt.Printf("Recorded skill pool: %s\n  -> %s\n", abs, p)
	return nil
}

// writeShims installs the `sr` alias next to the running binary.
//
// Windows gets TWO files on purpose. cmd.exe and PowerShell resolve `sr.cmd`
// via PATHEXT, but Git Bash does not consult PATHEXT — it looks for an
// extensionless file, which is why npm/bun and friends all ship both. Shipping
// only the .cmd would leave `sr` broken in exactly the shell most of this
// workspace's tooling runs in.
func writeShims() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate the running binary: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	dir := filepath.Dir(exe)

	for name, body := range shimFiles(exe) {
		p := filepath.Join(dir, name)
		// 0o755 so POSIX gets the execute bit; Windows ignores the mode (it has
		// no permission bits — os.Chmod there only toggles read-only).
		if err := os.WriteFile(p, []byte(body), 0o755); err != nil {
			return fmt.Errorf("write shim %s: %w", p, err)
		}
		fmt.Printf("Wrote shim: %s\n", p)
	}
	return nil
}

// shimFiles maps filename -> contents for the current platform. Split out from
// writeShims so the contents can be asserted without touching the filesystem.
//
// The wrappers call the binary by ABSOLUTE path rather than by name. They are
// generated at install time on the machine that will run them, so there is no
// cross-compilation hazard here, and an absolute path cannot be shadowed by
// another skillrunner earlier on PATH.
func shimFiles(exe string) map[string]string {
	if runtime.GOOS == "windows" {
		return map[string]string{
			// cmd.exe / PowerShell.
			shimName + ".cmd": "@\"" + exe + "\" %*\r\n",
			// Git Bash. Forward slashes: a POSIX shell treats backslash as an
			// escape, so C:\...\skillrunner.exe would be mangled.
			shimName: shimScript(filepath.ToSlash(exe)),
		}
	}
	return map[string]string{shimName: shimScript(exe)}
}

func shimScript(exe string) string {
	return "#!/bin/sh\n# Generated by `skillrunner home --shims`. Do not edit.\nexec \"" + exe + "\" \"$@\"\n"
}

// reportHome prints the resolved manifest and which rung produced it, plus the
// state of each rung, so a wrong answer can be traced without guessing.
func reportHome() error {
	path, via, err := resolveManifestPath("", ".")

	fmt.Println("Manifest resolution")
	if err != nil {
		fmt.Println("  resolved: (none)")
	} else {
		// Absolute, even when rung 2 produced a relative "skill.json": the whole
		// point of this command is to say WHICH pool is in play.
		shown := path
		if abs, aerr := filepath.Abs(path); aerr == nil {
			shown = abs
		}
		fmt.Printf("  resolved: %s\n  via:      %s\n", shown, via)
	}

	const label = "  %d. %-18s "
	fmt.Println("\nRungs, in priority order:")
	fmt.Printf(label+"(not given)\n", 1, "-f/--file")
	fmt.Printf(label+"%s\n", 2, "./"+manifestName, present(filepath.Join(".", manifestName)))
	if env := strings.TrimSpace(os.Getenv(homeEnv)); env != "" {
		fmt.Printf(label+"%s %s\n", 3, "$"+homeEnv, env, present(filepath.Join(env, manifestName)))
	} else {
		fmt.Printf(label+"(unset)\n", 3, "$"+homeEnv)
	}
	if p, perr := pointerPath(); perr == nil {
		if home, herr := pointerHome(); herr == nil && home != "" {
			fmt.Printf(label+"%s %s\n", 4, "pointer file", home, present(filepath.Join(home, manifestName)))
			fmt.Printf("  %-21s (%s)\n", "", p)
		} else {
			fmt.Printf(label+"(not set: %s)\n", 4, "pointer file", p)
		}
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "\n%v\n", err)
		os.Exit(1)
	}
	return nil
}

func present(p string) string {
	if fileExists(p) {
		return "[found]"
	}
	return "[missing]"
}
